-- ANU Explore new dorm label seed
-- Run once in Supabase SQL Editor after patch-dorm-detail-editor.sql.
--
-- Note:
-- Burgman College is represented by one editable dorm row on building 1032.
-- The other Burgman member buildings stay grouped in config/functional-buildings.json
-- so the original map data remains clean and maintainable.

insert into public.building_label_overrides (
  building_number,
  building_id,
  display_mode,
  type_key,
  display_name,
  short_name,
  interactive,
  label_enabled,
  dorm_tag,
  dorm_rent_text,
  dorm_type,
  dorm_location,
  dorm_summary,
  dorm_description,
  dorm_best_for,
  dorm_location_feel,
  dorm_trade_off
) values
  (
    '1113',
    'dorm_yukeembruk',
    'dorm',
    'dorm',
    'Yukeembruk',
    'Yukeembruk',
    true,
    true,
    'PLACEHOLDER / RESIDENCE',
    'Not listed',
    'Residential hall',
    'ANU campus',
    'Placeholder residence profile for Yukeembruk.',
    'Yukeembruk is now linked to the Explore map as a usable dorm label. Detailed residence content is pending.',
    'Placeholder profile for future dorm comparison, map navigation, and residence detail content.',
    'Location and living feel are pending detailed content review.',
    'This profile is currently a functional placeholder and should be refined later.'
  ),
  (
    '892',
    'dorm_wamburn',
    'dorm',
    'dorm',
    'Wamburn Hall',
    'Wamburn',
    true,
    true,
    'PLACEHOLDER / RESIDENCE',
    'Not listed',
    'Residential hall',
    'ANU campus',
    'Placeholder residence profile for Wamburn Hall.',
    'Wamburn Hall is now linked to the Explore map as a usable dorm label. Detailed residence content is pending.',
    'Placeholder profile for future dorm comparison, map navigation, and residence detail content.',
    'Location and living feel are pending detailed content review.',
    'This profile is currently a functional placeholder and should be refined later.'
  ),
  (
    '585',
    'dorm_bruce_packed_wing',
    'dorm',
    'dorm',
    'Bruce Hall Packed Wing',
    'Bruce Packed',
    true,
    true,
    'PLACEHOLDER / RESIDENCE',
    'Not listed',
    'Residential hall',
    'ANU campus',
    'Placeholder residence profile for Bruce Hall Packed Wing.',
    'Bruce Hall Packed Wing is now linked to the Explore map as a usable dorm label. Detailed residence content is pending.',
    'Placeholder profile for future dorm comparison, map navigation, and residence detail content.',
    'Location and living feel are pending detailed content review.',
    'This profile is currently a functional placeholder and should be refined later.'
  ),
  (
    '986',
    'dorm_ursula_main_wing',
    'dorm',
    'dorm',
    'Ursula Hall Main Wing',
    'Ursula Main',
    true,
    true,
    'PLACEHOLDER / RESIDENCE',
    'Not listed',
    'Residential hall',
    'ANU campus',
    'Placeholder residence profile for Ursula Hall Main Wing.',
    'Ursula Hall Main Wing is now linked to the Explore map as a usable dorm label. Detailed residence content is pending.',
    'Placeholder profile for future dorm comparison, map navigation, and residence detail content.',
    'Location and living feel are pending detailed content review.',
    'This profile is currently a functional placeholder and should be refined later.'
  ),
  (
    '1330',
    'dorm_graduate_house',
    'dorm',
    'dorm',
    'Graduate House',
    'Graduate',
    true,
    true,
    'PLACEHOLDER / RESIDENCE',
    'Not listed',
    'Residential hall',
    'ANU campus',
    'Placeholder residence profile for Graduate House.',
    'Graduate House is now linked to the Explore map as a usable dorm label. Detailed residence content is pending.',
    'Placeholder profile for future dorm comparison, map navigation, and residence detail content.',
    'Location and living feel are pending detailed content review.',
    'This profile is currently a functional placeholder and should be refined later.'
  ),
  (
    '1030',
    'dorm_john_xxiii',
    'dorm',
    'dorm',
    'John XXIII College',
    'John XXIII',
    true,
    true,
    'PLACEHOLDER / RESIDENCE',
    'Not listed',
    'Residential hall',
    'ANU campus',
    'Placeholder residence profile for John XXIII College.',
    'John XXIII College is now linked to the Explore map as a usable dorm label. Detailed residence content is pending.',
    'Placeholder profile for future dorm comparison, map navigation, and residence detail content.',
    'Location and living feel are pending detailed content review.',
    'This profile is currently a functional placeholder and should be refined later.'
  ),
  (
    '1032',
    'dorm_burgman',
    'dorm',
    'dorm',
    'Burgman College',
    'Burgman',
    true,
    true,
    'PLACEHOLDER / RESIDENCE',
    'Not listed',
    'Residential hall',
    'ANU campus',
    'Placeholder residence profile for Burgman College.',
    'Burgman College is now linked to the Explore map as a unified multi-building dorm label. Detailed residence content is pending.',
    'Placeholder profile for future dorm comparison, map navigation, and residence detail content.',
    'Location and living feel are pending detailed content review.',
    'This profile is currently a functional placeholder and should be refined later.'
  )
on conflict (building_number) do update
set
  building_id = excluded.building_id,
  display_mode = excluded.display_mode,
  type_key = excluded.type_key,
  interactive = excluded.interactive,
  label_enabled = excluded.label_enabled,
  display_name = coalesce(public.building_label_overrides.display_name, excluded.display_name),
  short_name = coalesce(public.building_label_overrides.short_name, excluded.short_name),
  dorm_tag = coalesce(public.building_label_overrides.dorm_tag, excluded.dorm_tag),
  dorm_rent_text = coalesce(public.building_label_overrides.dorm_rent_text, excluded.dorm_rent_text),
  dorm_type = coalesce(public.building_label_overrides.dorm_type, excluded.dorm_type),
  dorm_location = coalesce(public.building_label_overrides.dorm_location, excluded.dorm_location),
  dorm_summary = coalesce(public.building_label_overrides.dorm_summary, excluded.dorm_summary),
  dorm_description = coalesce(public.building_label_overrides.dorm_description, excluded.dorm_description),
  dorm_best_for = coalesce(public.building_label_overrides.dorm_best_for, excluded.dorm_best_for),
  dorm_location_feel = coalesce(public.building_label_overrides.dorm_location_feel, excluded.dorm_location_feel),
  dorm_trade_off = coalesce(public.building_label_overrides.dorm_trade_off, excluded.dorm_trade_off);

select
  building_number,
  building_id,
  display_name,
  short_name,
  interactive,
  label_enabled
from public.building_label_overrides
where building_number in ('1113', '892', '585', '986', '1330', '1030', '1032')
order by building_number;
